### PR TITLE
Berry fix round 4

### LINKED ISSUE #1068: [BUG] Kanto Berrymaster is showing always the same tip (?)
**Info**
 - OS: Windows 10
 - Browser Firefox

**Description:**
So far since the farm update, Kanto Berrymaster is showing always the same tip for me (#19 legendary berry).
Isn't the tip supposed to be updated each day?

### LINKED ISSUE #1075: [BUG] Unable to mulch multiple times in farm
**Info**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.6.3

**Description:**
Unable to mulch multiple times in farm

**Steps to Reproduce:**
1. Open Farm modal
2. Go to Mulch tab
3. Switch to a different mulch (works before changing mulch type)
4. Try applying multiple times to 1 plot

**Expected Behavior:**
Mulch should be stackable on plots

**Additional Information:**
Works as expected before changing mulch types

### PR DESCRIPTION
**Pull request by HLXII**
- Fix coin image for Oak Items, so Farm Coins now appear correctly
 - Increment Harvested Berries on Wither as well
 - Add Starters to wandering pokemon
 - Fix Maranga Mutation, which would produce only Kee Berries (woops)
 - Refactor Flavor Mutations. This should make it a bit harder to obtain now.
 - Hide Locked Berries in Berry Master Trades 
 - Buff mutation rates of Second Generation, to make them a bit easier than the first flavor mutations
 - Fixing mulches not working after one application
 - Fixing 5th gen mutations that caused errors (no one found this yet since they're still at 3rd gen max).
 - Updated Berry Quests to be based on region and also balanced QT rewards.
 - Implemented Enigma Hints in Kanto Berry Master and Berry Dex.
 - Add mulch descriptions to mulch list in Farm Modal
 - Fix Kanto Berry Master Daily hint updates. Will now update correctly as the date changes
 - Fix lag caused by Farm Update (at least the scrolling lag over time).

closes #1068 
closes #1075

### CODE REVIEW

File: src/scripts/farming/Farming.ts [hunk 1]
```diff
@@ -1026,8 +1025,6 @@ class Farming implements Feature {
 
         const amount = plot.harvestAmount();
 
-        GameHelper.incrementObservable(App.game.statistics.totalBerriesHarvested, amount);
-        GameHelper.incrementObservable(App.game.statistics.berriesHarvested[plot.berry], amount);
```
Comment (RedSparr0w) [inline src/scripts/farming/Farming.ts:1030]: Do you think it would it be worth having a "totalManualPlotsHarvested" statistic or similar?

File: src/scripts/farming/Farming.ts [hunk 2]
```diff
@@ -1233,8 +1233,9 @@ class Farming implements Feature {
         }
     }
 
+    public static genBounds = [0, 8, 20, 35, 53, Infinity];
```
Comment (RedSparr0w) [inline src/scripts/farming/Farming.ts:1236]: Do we need the `0` in here?
As then the numbers correctly correlate to the region IDs
```suggestion
    public static genBounds = [8, 20, 35, 53, Infinity];
```

File: src/scripts/farming/Farming.ts [hunk 3]
```diff
@@ -1233,8 +1233,9 @@ class Farming implements Feature {
...
     public static getGeneration(gen: number): BerryType[] {
-        const genBounds = [0, 8, 20, 35, 53, Infinity];
+        const genBounds = Farming.genBounds;
         return App.game.farming.berryData.filter(berry => berry.type >= genBounds[gen] && berry.type < genBounds[gen + 1]).map(berry => berry.type);
```
Comment (RedSparr0w) [inline src/scripts/farming/Farming.ts:1239]: For the above change to work:
```suggestion
        const minBound = genBounds[gen - 1] || 0;
        const maxBound = genBounds[gen] || Infinity;
        return App.game.farming.berryData.filter(berry => berry.type >= minBound && berry.type < maxBound).map(berry => berry.type);
```

File: src/scripts/quests/QuestHelper.ts [hunk 4]
```diff
@@ -86,16 +86,29 @@ class QuestHelper {
                 amount = SeededRand.intBetween(100, 500);
                 return new UseOakItemQuest(oakItem, amount);
             case 'HarvestBerriesQuest':
+                const berryRegionBound = Farming.genBounds[Math.min(player.highestRegion() + 1, 5)];
```
Comment (RedSparr0w) [inline src/scripts/quests/QuestHelper.ts:89]: Remove `+1` addition to `highestRegion`.
Better not to use magic numbers where possible.
```suggestion
                const berryRegionBound = Farming.genBounds[Math.min(player.highestRegion(), GameConstants.Region.unova)];
```

File: src/scripts/quests/QuestHelper.ts [hunk 5]
```diff
@@ -86,16 +86,29 @@ class QuestHelper {
...
+                    if (berry <= BerryType.None) {
+                        return false;
+                    }
+                    if (berry >= berryRegionBound) {
+                        return false;
+                    }
+                    if (App.game.farming.berryData[berry].growthTime[3] >= 6 * 60 * 60) {
+                        return false;
+                    }
+                    return true;
```
Comment (RedSparr0w) [inline src/scripts/quests/QuestHelper.ts:101]:
```suggestion
					// Needs to be a berry that can be planted
                    return berry != BerryType.None 
                    	// Need to be able obtain within our highest region
                    	&& berry < berryRegionBound
                    	// Needs to take less than 6 hours to fully grow
                    	&& App.game.farming.berryData[berry].growthTime[3] < 6 * 60 * 60;
```

File: src/scripts/quests/QuestHelper.ts [hunk 6]
```diff
@@ -86,16 +86,29 @@ class QuestHelper {
...
+                });
+
                 const berryType = SeededRand.fromArray(berryTypes);
                 // Calculating balanced amount based on BerryType
                 // Hard limits are between 10 and 300
                 // Additional limits based on growing on all 25 plots non-stop in 6 hours
```
Comment (RedSparr0w) [inline src/scripts/quests/QuestHelper.ts:107]:
```suggestion
                // Additional limits based on growing on all 25 plots non-stop in 3 hours
```

**Review by RedSparr0w — CHANGES_REQUESTED** [review]
Awesome work thanks,
Just a couple small things.

File: src/scripts/farming/Farming.ts [hunk 7]
```diff
@@ -1083,7 +1082,11 @@ class Farming implements Feature {
         }
 
         amount = Math.min(this.mulchList[mulch](), amount);
+
         GameHelper.incrementObservable(this.mulchList[mulch], -amount);
+        GameHelper.incrementObservable(App.game.statistics.totalMulchesUsed, amount);
+        GameHelper.incrementObservable(App.game.statistics.mulchesUsed[+mulch], amount);
```
Comment (RedSparr0w) [inline src/scripts/farming/Farming.ts:1088]: We shouldn't need to use `+mulch` anymore, as it should always be a number due to the ko extend.
```suggestion
        GameHelper.incrementObservable(this.mulchList[mulch], -amount);
        GameHelper.incrementObservable(App.game.statistics.totalMulchesUsed, amount);
        GameHelper.incrementObservable(App.game.statistics.mulchesUsed[mulch], amount);
```

**Review by RedSparr0w — APPROVED** [review]
