### PR TITLE
Berry fixes round 5

### LINKED ISSUE #1078: [BUG] TypeError in EnigmaMutation unlock requirement check
**Info**
 - OS: Windows 10
 - Browser: Chrome/Firefox
 - Version: v0.6.3/v0.6.4

**Description:**
After unlocking the Wepear berry, the console gets spammed with TypeErrors caused by the EnigmaMutation trying to check whether we unlocked berry #67, which doesn't exist.

**Steps to Reproduce:**
1. Unlock the Wepear berry
2. Check the console

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by HLXII**
- Fix Hondew mutation to match actual Berry flavor and be harder.
 - Update Enigma mutation algorithm to use 2nd and 3rd gen berries. So nobody can get Cheri and Starf as two requirements (which would suck lol). The berry timers should be closer with 2nd and 3rd gens. This also closes #1078 
 - Fix typo from "Ringo" to "Rindo"
 - Change some wording in the Farm Help menu to be more clear
 - Mutation balance changes
 - Nerf Auras quite a bit
 - Boost wandering pokemon shiny chance.

### CODE REVIEW

File: src/scripts/farming/mutation/Mutation.ts [hunk 1]
```diff
@@ -73,6 +73,14 @@ abstract class Mutation implements Saveable {
         return '';
     }
 
+    /**
+     * Handles getting the mutation chance
+     * @param idx The plot index
+     */
+    mutationChance(idx: number): number {
+        return this._mutationChance;
+    }
```
Comment (RedSparr0w) [inline src/scripts/farming/mutation/Mutation.ts:82]: This doesn't seem to be doing anything different than the old variable?
`idk` is never used either.

Comment (HLXII) [reply src/scripts/farming/mutation/Mutation.ts:82]: Adding it so it can be overriden in the GrowNearFlavorMutation class.

File: src/scripts/towns/Town.ts [hunk 2]
```diff
@@ -911,9 +911,6 @@ const CanalaveCityShop = new Shop ([
 const PalParkShop = new Shop([
     ItemList['Razor_claw'],
     ItemList['Razor_fang'],
-    ItemList['Combee'],
-    ItemList['Burmy (plant)'],
-    ItemList['Cherubi'],
```
Comment (RedSparr0w) [inline src/scripts/towns/Town.ts:916]: I don't think we should completely remove these from the shops yet.

File: src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts [hunk 3]
```diff
@@ -48,4 +48,30 @@ class GrowNearFlavorMutation extends GrowNearMutation {
...
+    /**
+     * Handles getting the mutation chance.
+     * Will decrease the mutation chance if the mutatedBerry already exists around this one.
+     * @param idx The plot index
+     */
+    mutationChance(idx: number): number {
+        const plots = Plot.findNearPlots(idx);
+        if (!plots.length) {
+            return 0;
+        }
```
Comment (RedSparr0w) [inline src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts:60]: In the unlikely event this does happen, should it not just return the default mutation chance?
```suggestion
        if (!plots.length) {
            return super.mutationChance(idx);
        }
```

File: src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts [hunk 4]
```diff
@@ -48,4 +48,30 @@ class GrowNearFlavorMutation extends GrowNearMutation {
...
+            if (!plot.isUnlocked) {
+                return;
+            }
+            if (plot.isEmpty()) {
+                return;
+            }
+            if (plot.berry === this.mutatedBerry) {
+                sameBerries += 1;
+            }
+        });
```
Comment (RedSparr0w) [inline src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts]: This can be simplified a bit:
```suggestion
        const sameBerries = Plot.findNearPlots(idx).reduce((acc, plotIndex) => {
            return App.game.farming.plotList[plotIndex].berry === this.mutatedBerry ? acc + 1 : acc;
        }, 1);
```
or
```suggestion
        const sameBerries = Plot.findNearPlots(idx).filter(plotIndex => {
            return App.game.farming.plotList[plotIndex].berry === this.mutatedBerry;
        }).length;
```

File: src/components/farmModal.html [hunk 5]
```diff
@@ -195,13 +195,13 @@ <h4><u>Farm</u></h4>
...
                     <p>Otherwise after some time being fully grown, the Berry plant will wither away,
-                    dropping only a fraction of the Berries but may also be re-planted automatically.
+                    dropping half of the expected Berries but may also be re-planted automatically.
                     <br/><i>(Farm Points are only gained by manually harvesting Berries)</i><p>
 
                     <p>Additional plots can be unlocked by spending Berries.</p>
 
                     <h4><u>Mutations</u></h4>
-                    <p>Berries have the chance to mutate into other Berries based on certain conditions.
+                    <p>Berries have the chance to cause mutations and create new Berry species based on certain conditions.
```
Comment (RedSparr0w) [inline src/components/farmModal.html:204]: This seems to also be a common source of confusion:
```suggestion
                    <p>Berries have the chance to cause mutations and create new Berry species in empty plots based on certain conditions.
```

Comment (HLXII) [reply src/components/farmModal.html:204]: Only issue is that some mutations don't require empty plots. Not sure if we want that distinction in the help tab though.

Comment (RedSparr0w) [reply src/components/farmModal.html:204]: Maybe in the hint text for those few we can specify that it will actually change the berry?

File: src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts [hunk 6]
```diff
@@ -48,4 +48,30 @@ class GrowNearFlavorMutation extends GrowNearMutation {
...
```
Comment (RedSparr0w) [inline src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts]: This can be simplified a bit with a reduce or filter:
```suggestion
        const sameBerries = plots.reduce((acc, plotIndex) => {
            return App.game.farming.plotList[plotIndex].berry === this.mutatedBerry ? acc + 1 : acc;
        }, 1);
```
or
```suggestion
        const sameBerries = plots.filter(plotIndex => {
            return App.game.farming.plotList[plotIndex].berry === this.mutatedBerry;
        }).length;
```

File: src/components/farmModal.html (hunk 5 above)
Comment (HLXII) [reply src/components/farmModal.html]: I'm okay with changing it to "in empty plots". Hopefully that doesn't confuse the player later on with evolve mutations though.

File: src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts (hunk 6 above)
Comment (RedSparr0w) [reply src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts]: 😓 Updated this comment because the old one was outdated, but you've already updated it lol, too quick

File: src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts [hunk 7]
```diff
@@ -54,23 +54,9 @@ class GrowNearFlavorMutation extends GrowNearMutation {
...
-                return;
-            }
-            if (plot.berry === this.mutatedBerry) {
-                sameBerries += 1;
-            }
-        });
+        const sameBerries = Plot.findNearPlots(idx).filter(plotIndex => {
+            return App.game.farming.plotList[plotIndex].berry === this.mutatedBerry;
+        }).length;
         return super.mutationChance(idx) * Math.pow(10, -sameBerries);
```
Comment (RedSparr0w) [inline src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts:60]: Is it expected that this will basically destroy the chances of mutation for the same berry if there is 1 or more?

Comment (HLXII) [reply src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts:60]: Yea it'll kill the invasiveness. I added 10 just randomly. We could scale it down to 5 or something if you still want some reproduction occurring.

Comment (RedSparr0w) [reply src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts:60]: I feel like anywhere between `2` and `5` should cut down the odds enough that it doesn't become so invasive,

Comment (HLXII) [reply src/scripts/farming/mutation/mutationTypes/GrowNearFlavorMutation.ts]: I'll put it at 4 for now, hopefully that'll curb it still.

**Review by RedSparr0w — APPROVED** [review]
Changes look good, thanks for the PR!
