### PR TITLE
Log oak item use statistic even at max level

### LINKED ISSUE #489: [BUG] OakItem quests don't progress is the oakItem is at max level
Quests that require you 'get the benefit' from an Oak Item don't tick up if the Oak Item is already at max level. 

Check the `OakItem.use()` method to see what goes wrong and how you can fix it :)

### PR DESCRIPTION
**Pull request by fujnw**
Closes #489

### CODE REVIEW

File: src/scripts/oakItems/OakItem.ts [hunk 1]
```diff
@@ -23,12 +23,13 @@ class OakItem extends ExpUpgrade {
     }
 
     use(exp: number = this.expGain) {
-        if (this.isMaxLevel() || !this.isActive) {
+        if (!this.isActive) {
             return;
         }
-
+        if (!this.isMaxLevel()) {
+            this.gainExp(exp);;
```
Comment (Ishadijcks) [inline src/scripts/oakItems/OakItem.ts]:
```suggestion
            this.gainExp(exp);
```
